### ISSUE TITLE
顶点缓存部分文章需要更新，代码片段无法访问

### ISSUE THREAD

**Issue by Ryu613** [fangcun010/VulkanTutorialCN#13]
顶点缓存部分需要更新，代码片段无法访问(原址已更新)，导致源代码无法编译通过
正文部分缺失代码片段，如“22顶点输入描述“一节中，缺少代码片段，正文也缺漏这部分内容。
参考：https://vulkan-tutorial.com/Vertex_buffers/Vertex_input_description
Binding descriptions段落和其下的文章，在译文中都没有
我一路读下来，目前到此处，总体来说，可能由于原文有更新，有部分源码和和文章，和原文对应不上，些许错别字，算作小问题，需要更新修校。
原文中"compute shader"部分暂时没翻译
提个建议，原文标题应该为”Vulkan教程“之类可能更好，因为”编程指南“的表述可能与另一本书"Vulkan Programming Guide"的名字冲突

总体感谢作者的分享和提供翻译！

**Comment by fangcun010** [comment]
感谢反馈！

需要感觉不对的问题，可以直接提交PR修改。
compute shader章节是新添加的，目前官方原版翻译正在校对，欢迎提交PR到原版。
