### ISSUE TITLE
关于中文翻译站建设的建议

### ISSUE THREAD

**Issue by FlyAndNotDown** [fangcun010/VulkanTutorialCN#3]
看了作者的翻译，感觉很棒，不过个人觉得技术类的文档使用网站更好，也更容易推广，不知道作者是否有建设中文翻译站的打算？

ps：可以参考 [LearnOpenGL-CN](https://learnopengl-cn.github.io/) 和 [LearnOpenGL](https://learnopengl.com/)

**Comment by fangcun010** [comment]
暂时没有，但翻译和原文一样都是CC协议，不阻止其他人这样做。------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月12日(星期三) 上午9:42
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[fangcun010/VulkanTutorialCN] 关于中文翻译站建设的建议 (#3)

**Comment by FlyAndNotDown** [comment]
了解了 😂

**Comment by leosongwei** [comment]
也许可以整个脚本，把那个tex文件parse出来，拆成网页，然后转换成网站，进一步地就能用github博客部署了
