### ISSUE TITLE
感觉内容和英文书有点对不上

### ISSUE THREAD

**Issue by denghe** [fangcun010/VulkanTutorialCN#8]
英文书的序 里提到了  M1,  C++17

**Comment by zeromake** [comment]
@denghe 
看了一下原书是 Aug 15, 2021 添加的内容，这个仓库是 Mar 22, 2019 添加的
https://github.com/Overv/VulkanTutorial/commits/main/en/00_Introduction.md

**Comment by fangcun010** [comment]
> @denghe 看了一下原书是 Aug 15, 2021 添加的内容，这个仓库是 Mar 22, 2019 添加的 https://github.com/Overv/VulkanTutorial/commits/main/en/00_Introduction.md

M1相关内容是新添加的。
